import IAbout from './IAbout';
import IAgb from './IAgb';
import IArtists from './IArtists';
import IAudio from './IAudio';
import IBiography from './IBiography';
import IConcerts from './IConcerts';
import ICV from './ICV';
import IEnsembles from './IEnsembles';
import IEvents from './IEvents';
import IHero from './IHero';
import IHome from './IHome';
import IImpressum from './IImpressum';
import IInstruments from './IInstruments';
import Menu from './IMenu';
import IProjects from './IProjects';
import ISettings from './ISettings';
import ISlider from './ISlider';
import IVideos from './IVideos';

export default interface IData {
  timeStamp: string;
  biography: IBiography[];
  artists: IArtists[];
  home: IHome[];
  instruments: IInstruments[];
  projects: IProjects[];
  events: IEvents[];
  hero?: IHero[];
  about?: IAbout[];
  cv?: ICV[];
  slider?: ISlider[];
  videos?: IVideos[];
  audio?: IAudio[];
  ensembles?: IEnsembles[];
  concerts: IConcerts[];
  agb: IAgb[];
  impressum: IImpressum[];
  settings: ISettings[];
  menu: Menu[];
}